// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6mic7UxmCJ7sBmUkZJNgwqfW8YH5pazI',
    appId: '1:77103938701:web:4664080e609d17112336c4',
    messagingSenderId: '77103938701',
    projectId: 'couple-split-app-6d55a',
    authDomain: 'couple-split-app-6d55a.firebaseapp.com',
    storageBucket: 'couple-split-app-6d55a.firebasestorage.app',
    measurementId: 'G-QXHPFZM6PV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOpKi8pt0xdNpbprQKOMLfvQuDdzYQ-5I',
    appId: '1:77103938701:android:3b8f3a7f5d22ee082336c4',
    messagingSenderId: '77103938701',
    projectId: 'couple-split-app-6d55a',
    storageBucket: 'couple-split-app-6d55a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5AGhO-q5rbhUkSinZIK-E2UYAhaUOTMk',
    appId: '1:77103938701:ios:65495f8762e285b62336c4',
    messagingSenderId: '77103938701',
    projectId: 'couple-split-app-6d55a',
    storageBucket: 'couple-split-app-6d55a.firebasestorage.app',
    iosBundleId: 'com.example.coupleSplitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5AGhO-q5rbhUkSinZIK-E2UYAhaUOTMk',
    appId: '1:77103938701:ios:65495f8762e285b62336c4',
    messagingSenderId: '77103938701',
    projectId: 'couple-split-app-6d55a',
    storageBucket: 'couple-split-app-6d55a.firebasestorage.app',
    iosBundleId: 'com.example.coupleSplitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6mic7UxmCJ7sBmUkZJNgwqfW8YH5pazI',
    appId: '1:77103938701:web:46a37d3fe470b0522336c4',
    messagingSenderId: '77103938701',
    projectId: 'couple-split-app-6d55a',
    authDomain: 'couple-split-app-6d55a.firebaseapp.com',
    storageBucket: 'couple-split-app-6d55a.firebasestorage.app',
    measurementId: 'G-99FQVKDMGM',
  );

}